config/routes.rb
Rails.application.routes.draw do
  root to: 'employers#index'
  devise_for :users
  #devise_for :employers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root to: "employees#index"
  resources :employers ,only: [] do
    collection do
      get :acco
      get :get_acco
      get :new
      post :create
    end
  end


  resources :employees ,except: [:show] do
    collection do    
      get "employees_destroy"
    end
  end
  resources :members
  resources :roles 
  resources :designations
  resources :addresses ,except: [:show]
  get "search" ,to: "employees#search"
  
  get "employees/address(/:id)" ,to: "employees#adda" ,as: 'adres'

  get "employees/grouping" ,to: "employees#grouping" 
  
end

app/models/employee.rb
class Employee < ApplicationRecord
	paginates_per 4
	belongs_to :employer
	has_many :addresses ,dependent: :delete_all #,inverse_of: :address 
	accepts_nested_attributes_for :addresses , allow_destroy: true  ,reject_if: :checking?

	acts_as_paranoid

	has_one_attached :image

	belongs_to :designation


	#validates :first_name , :last_name ,presence: true ,format: { with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/,
   # message: "only allows letters" }
  after_create  :registration_email
	
	validates :doj , :dob  ,presence: true
	validates :email , presence: true ,uniqueness: true
	

	def self.search_employee(search , designate)	
		if designate.nil? or designate == '0'	
      where("name LIKE :q OR email LIKE :q " ,q: "%#{search}%")
    else
    	design = where("designation_id IS :d" ,d: "#{designate}")
    	design.where("first_name LIKE :q OR last_name LIKE :q OR email LIKE :q " ,q: "%#{search}%")
    end
  end

	private
	def checking?(attr)
		attr['country'].blank? and attr['state'].blank?  and attr['city'].blank? and attr['street_address'].blank?
	end
	def registration_email
		
		#EmployeeMailer.new_employee(self.employee).deliver
	end
end

app/models/employer.rb
class Employer < ApplicationRecord
  has_many :employees ,dependent: :destroy
  belongs_to :user
  has_many :memberships ,dependent: :destroy
  after_create :create_admin
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  private
  def create_admin
    employerin = Employer.last
    employersid= employerin.id
    userin = employerin.user_id
    Membership.create(user_id: userin,role_id: 4 ,user_role: userin ,employer_id: employersid)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!

  before_action :require_employee ,only: [:edit ,:adda ,:update]

  def index
    @employees = currents_employer.employees.search_employee(params[:search] , params[:designate])
    @empl = @employees.page(params[:page])
  end

  def show  
  end

  def new   
    @employee = Employee.new
    2.times { @employee.addresses.new }
  end

  def create
    @employee = currents_employer.employees.new(param_employee)
    if @employee.save   
      redirect_to '/employees'
    else 
      render 'new'
    end
  end


  def edit
  end

  def update    
    if @employee.update(param_employee_update)   
      flash[:notice] = "#{@employee.first_name} is updated" 
      redirect_to '/'
    else 
      render 'edit'
    end 
  end

  def destroy
    @identity = @employee.id
    @employee.destroy
    @employees = currents_employer.employees
    #redirect_to '/employees'
    respond_to do |format|
      format.js 
    end
  end

  def adda
    @addrs  = @employee.addresses
  end

  def grouping
    @group = currents_employer.employees.group("designation_id")
  end

  def employees_destroy
    @employee_ids = params[:index_array]
    @id_size = params[:index_array].size
    @employee = Employee.where(id: @employee_ids)
    @employee.destroy_all
    @employees = currents_employer.employees
    respond_to :js
  end

  private

  def param_employee    
    permanent_address
    params.require(:employee).permit(:name , :email, :dob ,:mobile,
     :doj,:designation_id ,:image,addresses_attributes: [:address_types , :country, :state , :city , :street_address,:_destroy , :chek] )
  end
  
  def param_employee_update
    params.require(:employee).permit(:first_name,:last_name,:mobile,:email,:dob,:doj)
  end

  def require_employee  
    @employee = currents_employer.employees.find(params[:id])
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<form name="myForm" action="/employees" onsubmit="return Validation()"  method="post" enctype="multipart/form-data">
<div class="card" align="">
   
<div class="col-lg-4 col-offset-9 centered">
<%= form_with model: @employee  do |form| %>

<%= form.file_field :image %><h6 style="color:blueviolet;">upload your image here.</h6><br>

<%= form.select :designation_id , options_for_select(Designation.all.collect{|p| [p.desig_name,p.id]}) %>

<div class="form-group" >
  First_Name => <%= form.text_field  :name ,{ class: "form-control"}%>

  <span style="font-color:red;" id = "fspan"></span> 

  <% @employee.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>

  


  <div class="form-group">
  Email=> <%= form.email_field  :email , { class: "form-control"}%>
  <span id="espan"></span>
  <% @employee.errors.full_messages_for(:email).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>
  
  <div class="form-group">
  Mobile=> <%= form.text_field  :mobile , { class: "form-control"  } %>
  <span id="mspan"> </span>
  <% @employee.errors.full_messages_for(:mobile).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  D.o.B=> <%= form.date_field  :dob ,{ class: "form-control"}%>  
  <span id="dobspan"> </span>
    <br>   ,
 D.o.J=> <%= form.date_field  :doj ,{ class: "form-control"} %>
 <span id="dojspan"></span>
  </div></div></div>
  
  Address=> 
  <% a = 0 %>
  <div align="center">
  <div class="card" >
   <div class="form-group" >
  <br><%= form.fields_for :addresses  do |add| %>
  
<div class="col-lg-4 ">
  
  <div id =  "one<%=a%>">>
  <span style="color:red">
   <%= @lebel = "please write your #{@first} address here" %>
 </span>
  <div style="" align="center" >
  <p>
    <%#= add.label :address_types %>
   <%#= add.select :address_types ,['Current','Permanent'],{include_blank: true}, placeholder: "address_types"%> 

   <%= add.hidden_field :address_types ,:value => @first , include_blank: true %>
    

    <%#= add.label :country %><div>
    <%= add.text_field :country ,{ class: "form-control",  placeholder: "country" }%>

    <%#= add.label :state %>
    <%= add.text_field :state , { class: "form-control" , placeholder: "State" }%>

    <%#= add.label :city  %>
    <%= add.text_field :city ,{ class: "form-control" , placeholder: "city" }%>              

    <%#= add.label :Street_Address %>
    <%= add.text_field :street_address ,{ class: "form-control",  placeholder: "street_address" }%>
  
  </p>
</div></div>
<% @first = "Permanent" %>

  
  <% if a == 0 %>
    <div id= "boxe"> <%= add.check_box :chek, class: "address-permanent" %>Do u have same permanent Address?</div>
  <% a = 1 %>
  <% end %>
  <% @first = "Permanent" %>
</div></div></p>
  <% end %></div></div>
  <br><%#= form.fields_for :designations  do |desig| %>
  <div class="form-group">

<span id="desigspan"></span>
 </div></p>
<br><br>
<%#= desig.select :user_id, options_for_select(@users.collect { | user | [user.name, user.id] }, @user.id), {}, {} %>
<%# end %>
  <br>
  <%= form.submit 'Employee_Signup' , data: { disable_with: false } %>
  <% end %>

  <div id = "designation_ids"> <%= raw Designation.ids.to_a %></div>
</div>
</form>

app/views/employees/_indexrecord.html.erb
<h3><%= link_to 'New_Employee' , new_employee_path %></h3>
<%# if @employees.blank? %>
  
<!--   <div>
    <h1 align="center" style="color:red"><%#= "Record not Found.!" %></h1>
  </div>
   -->
<%# end %>
<div class="container"> 
<div class="row">
    <%  @employees.each do |epr|  %>
      <% @de = Designation.find_by_id(epr.designation_id) %>
      <div class="col-md-3"  id="record<%=epr.id%>" > 
        <div class="card" id="mouse<%= epr.id%>" onmouseover="mouseIn(this.id)" onmouseout="mouseOut(this.id)">
        <div id="mouse<%=epr.id%>" >
              
        <% if epr.image.attached? %>
          <%= image_tag  url_for(epr.image) ,:size => "260x180" %>
        <% end %>
        <div class="card-body"  >
          <%= epr.id %>
          <h4 class="card-title"> <%= epr.name %>
               
                 <div style="color:greenyellow;">(<%= @de.desig_name %>)</div></h4><br>
                  <table style="border:solid currentColor;">
                    <tr>
                      <td>Email</td>
                      <td><%= epr.email %></td>
                    </tr>
                    <tr>
                      <td>Mobile</td>
                      <td><%= epr.mobile %></td>
                    </tr>
                    <tr>
                      <td>D.o.B</td>
                      <td><%= epr.dob %></td>
                    </tr>
                    <tr>
                      <td>D.o.J</td>
                      <td><%= epr.doj %></td>
                    <tr>
                    <tr>
                      <td><%= link_to 'address' ,adres_path(epr.id) %> </td>
                      <td><input type='checkbox' value = "<%= epr.id %>" class = 'employee_index'></td>
                      <td><%= link_to 'edit',edit_employee_path(epr.id) %></td>
                    </tr>
                  </table>
                </div></div></div></div>
          

<% end %>
</div> </div>
    
   <div align="center"> <%= paginate @empl %></div>



    <div class="modal fade" id="myModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">   
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Are You Sure ?</h4>
        </div>
        <div class="modal-body">
          <p>You are destroying the the employees detail...</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
        
          <button type="button" class="btn btn-default" data-dismiss="modal">Yes</button>
        </div> 
      </div>
    </div>
    </div>



<script type="text/javascript">
function mouseIn(geted){
  document.getElementById(geted).style.fontColor = "red";
  document.getElementById(geted).style.backgroundColor = "#e0dede"
}

function mouseOut(geted){
  document.getElementById(geted).style.color = "black";
  document.getElementById(geted).style.backgroundColor = "#ffffff"
}
</script>

<style type="text/css">
  td, th {
    border: 1px solid #dddddd;
    text-align: center;
    padding: 5px; 
  }

  tr:nth-child(even) {
    background-color: #dddddd;
  }
  #collap{
    font-size: 30px;
  }
  table{
    width: 90%;
  }
}
</style>

app/views/employees/_research.html.erb
<%= javascript_pack_tag 'application' , 'data-turbolinks-track': 'reload' %>

<div class="navbar navbar-light bg-light" align="center">
  <div class="form-inline">
  
  <input type="text" id="searchbox">
  <button type="button" id="searchbutton" >Search</button>
   
</div>

</div>

<div class="navbar navbar-light bg-light" align="center">
  <div class="form-inline">
 <select  id="designations" placeholder="select designation">
  <option value="0">All designation</option>
<%= Designation.all.each do |designation| %>
  <option value="<%=designation.id%>"><%= designation.desig_name %></option>

 <% end %>
</select>
</div></div>

app/views/employees/adda.html.erb
<div class="container">

<% @addrs.each do |address| %>
<div class="jumbotron">
  Address => <%= address.address_types %> Address =>
  ID: <%= address.id %><br>
  Country : <%= address.country %><br>
  State : <%= address.state %> <br>
  City : <%= address.city %> <br>
  Street_address : <%= address.street_address %>
  <%= link_to 'edit' ,edit_address_path(address.id) %>
  <%= link_to 'delete' ,address_path(address.id) ,method: :delete ,data: {confirm: "Are You Sure" }%>
<br></div>

<% end %></div>

app/views/employees/destroy.js.erb
//document.querySelector("#demo" + <%=@identity%>).remove();
$("#record" + <%=@identity%>).remove()

app/views/employees/edit.html.erb
<br>
<h1>Updating_Employee Form =></h1><br>
<%= @lebel = "" %>

<%#= render 'form' %>
<%= form_with model: @employee  do |form| %>
<div class="form-group">
  First_Name => <%= form.text_field  :first_name ,{ class: "form-control", placeholder: "" }%>
  <% @employee.errors.full_messages_for(:first_name).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>

  
  <div class="form-group">
  Last_Name => <%= form.text_field  :last_name , { class: "form-control", placeholder: "" } %>
  <% @employee.errors.full_messages_for(:last_name).each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>
  


  <div class="form-group">
  Email=> <%= form.text_field  :email , { class: "form-control", placeholder: "" } %>
  <% @employee.errors.full_messages_for(:email).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>
  
  <div class="form-group">
  Mobile=> <%= form.text_field  :mobile , { class: "form-control" , placeholder: "" } %>
  <% @employee.errors.full_messages_for(:mobile).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>
  D.o.B=> <%= form.date_field  :dob ,{ class: "form-control"}%>    <br>   ,
 D.o.J=> <%= form.date_field  :doj ,{ class: "form-control"} %>
  </div></div></div>
  
  <br><%= form.fields_for :designations  do |desig| %>
<%= desig.select :id , options_for_select(Designation.all.collect{|p| [p.desig_name,p.id]}) , placeholder: "Designation" %>
<% end %>
<%#= desig.select :user_id, options_for_select(@users.collect { | user | [user.name, user.id] }, @user.id), {}, {} %>
<%= form.file_field :image %>
 <div class="btn btn-primary"> <%= form.submit 'Employee_Signup'%></div>

<% end %>

app/views/employees/employeesDestroy.js.erb
console.log(<%= raw @employee_ids %>)
a = <%= raw @employee_ids %>

for (let i = 0; i < <%= raw @id_size %>; i++) {
  $('#record'+a[i]).remove();
}

app/views/employees/employees_destroy.js.erb
console.log(<%= raw @employee_ids %>)
a = <%= raw @employee_ids %>

for (let i = 0; i < <%= raw @id_size %>; i++) {
  $('#record'+a[i]).remove();
}

app/views/employees/grouping.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<h2><%= link_to 'All_Designations' ,designations_path %> </h2>
<h2><%= link_to 'Back_to_Employees' ,employees_path %></h2>



<div id = "accordion">
<% @group.each do |gro| %>

<% group = Designation.find(gro.designation_id) %>

<h1 id = "collap"><%= group.desig_name %>s =></h1>

 <div>
 <table style="border:solid;" align="center" id="group">
 <h2>	<tr align="center" style="column-gap: 400px;">
  <th>ID</th>
  <th><h1>Name</h1></th>
		
		<th><h1>Email</h1></th>
		<th><h1>mobile</h1></th>
		
	</tr></h2>
   <h3><% group.employees.each do |employee| %>
  <tr><td><%= employee.id %></td>
   <td><h4> <%= employee.first_name %>
    <%= employee.last_name %></h4></td>
   <td> <h4> <%= employee.email %> </h4></td>
   <td><h4> <%= employee.mobile %> </h4> </td>
    <td><h4> <%= link_to 'edit',edit_employee_path(employee.id) %> </h4></td>
  </tr>
  <% end %>
  </h3>

 </table>
</div>


<% end %>
</div>
<style type="text/css">
  td, th {
    border: 1px solid #dddddd;
    text-align: center;
    padding: 8px; 
  }

  tr:nth-child(even) {
    background-color: #dddddd;
  }
  #collap{
    font-size: 30px;
  }
  table{
    width: 100%;
  }
}
</style>
<script type="text/javascript">
  $( function() {
    $( "#accordion" ).accordion();
  } );
</script>

app/views/employees/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

 </head>
<body >
<div id = 'indexpage' >
<%= render  'research' %>


<h1 style="color:blueviolet" >Employees </h1>

<div  align='right' >
  <i class="fab fa-male fa-2x"  id = 'delete_button' >Delete</i>
</div>

<% unless @employees.nil? %>
  <div id = "indexrecords">
  <%= render 'indexrecord' %>
  </div>
<% end %>
</div>

app/views/employees/index.js.erb
$("#indexrecords").html("<%= escape_javascript(render partial: 'employees/indexrecord',locals: {employees: @employees}) %>");

app/views/employees/new.html.erb
<br>
<h1>Employee Form =></h1><br>
<% @lebel = "Write here your #{@first} Address or Leave it blank" %>
<% @box = "boxe" %>
<% @first = "Current" %>
<%= render 'form' %>