config/routes.rb
Rails.application.routes.draw do
  root to: 'employers#index'
  devise_for :users
  #devise_for :employers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root to: "employees#index"
  resources :employers ,only: [] do
    collection do
      get :acco
      get :get_acco
      get :new
      post :create
    end
  end


  resources :employees ,except: [:show] do
    collection do    
      get "employees_destroy"
    end
  end
  resources :members
  resources :roles 
  resources :designations
  resources :addresses ,except: [:show]
  get "search" ,to: "employees#search"
  
  get "employees/address(/:id)" ,to: "employees#adda" ,as: 'adres'

  get "employees/grouping" ,to: "employees#grouping" 
  
end

app/models/designation.rb
class Designation < ApplicationRecord
	has_many :employees
end

app/controllers/designations_controller.rb
class DesignationsController < ApplicationController
  #before_action :authenticate_employer!
  before_action :find_designation ,only: [:edit , :update , :destroy]
  def index 
    @designations =  Designation.all
  end

  def new
    @designation = Designation.new
  end

  def create
    @designation = Designation.create(param_designation)
    if @designation.save
      redirect_to '/designations'
	  else
	    render 'new'
	  end
  end
  
  def edit

  end

  def update
  	if @designation.update(param_designation)
      flash[:notice] = "#{desig_name} is  updated!!!"
  	  redirect_to '/designations'
    else
      render 'edit'
    end
  end

  def destroy
    @designation.destroy
  end

  private
  def param_designation
  	params.require(:designation).permit(:desig_name)
  end

  def find_designation
    @designation = Designation.find(params[:id]) 
  end
end

app/helpers/designations_helper.rb
module DesignationsHelper
end

app/views/designations/_formnew.html.erb
<%= form_with model: @designation  do |f| %>
<h2>Desigantion_name = </h2> 
<%= f.text_field :desig_name %>
<%= f.submit %>
<% end %>

app/views/designations/edit.html.erb
<h1>Edit from</h1>
<%= render 'formnew' %>

app/views/designations/index.html.erb
<h3><%= link_to 'new_designation' ,new_designation_path %></h3><br>
<h3><%= link_to 'Back_to employees' ,employees_path %></h3>
<div class="conrtainer">
	<div class="row">
	<h1>	Designations =></h1>
 <% @designations.each do |desi| %>
 <div style="border:solid;">
 <h4>Designation_id =><%= desi.id %></h4><br>
  <h4> Designation_name => <%= desi.desig_name %></h4><%= link_to 'edit' ,edit_designation_path(desi.id) %> <%= link_to 'delete',designation_path(desi.id) ,method: :delete ,data: {confirm: "are u sure?"} %><br>
</div><br><br>
<% end %></div></div>

app/views/designations/new.html.erb
<h1>New Designation</h1>
<%= render 'formnew' %>