config/routes.rb
Rails.application.routes.draw do
  root to: 'employers#index'
  devise_for :users
  #devise_for :employers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root to: "employees#index"
  resources :employers ,only: [] do
    collection do
      get :acco
      get :get_acco
      get :new
      post :create
    end
  end


  resources :employees ,except: [:show] do
    collection do    
      get "employees_destroy"
    end
  end
  resources :members
  resources :roles 
  resources :designations
  resources :addresses ,except: [:show]
  get "search" ,to: "employees#search"
  
  get "employees/address(/:id)" ,to: "employees#adda" ,as: 'adres'

  get "employees/grouping" ,to: "employees#grouping" 
  
end

app/models/employer.rb
class Employer < ApplicationRecord
  has_many :employees ,dependent: :destroy
  belongs_to :user
  has_many :memberships ,dependent: :destroy
  after_create :create_admin
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  private
  def create_admin
    employerin = Employer.last
    employersid= employerin.id
    userin = employerin.user_id
    Membership.create(user_id: userin,role_id: 4 ,user_role: userin ,employer_id: employersid)
  end
end

app/controllers/employers_controller.rb
require 'intuit-oauth'
class EmployersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_employer , only: [:edit , :destroy ,:show]

  def index
    #@detail = Account.authorization_code_url.body
    @employers = Employer.find(searching_employer)
  end

  def show
    @employer = Employer.find(params[:id])
    @members = Membership.where(employer_id: params[:id])
  end

  def acco
    Account.authorization_code_url
  end

  def get_acco
    get_bearer =  Account.client.token.get_bearer_token(params["code"])
   # debugger
  end


  def new
    @employer = Employer.new
  end

  def create
    debugger
    @employer =  Employer.new(param_employer)
    @employer.user_id = current_user.id
    if @employer.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @employer = Employer.update(param_employer)
    if @employer.save
      flash[:alert] = "Employer is updated"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @employer.destroy
  end

  private

  def param_employer
    params.require(:employer).permit(:name ,:email ,:mobile , :address , :dob ,:doj)
  end

  def require_employer
    @employer = Employer.find(params[:id])
  end

  def searching_employer
    mem = Membership.where(user_role: current_user.id)
    emp = mem.pluck(:employer_id)
    emp1 = Employer.where(user_id: current_user.id )
    arr = emp1.ids + emp
    return arr
  end

end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_index.html.erb
<div id="employers">
<h3><%= link_to 'New_Employer' , new_employer_path %></h3>
<h2>Employers</h2>
<% @employers.each do |employer| %>
	<%= employer.name %><br>
<% end %>
</div>

app/views/employers/edit.html.erb
<div id="form" align="center">
<%= form_with model: @employer do |form| %>
Name 	<%= form.text_field :name %><br><br>
Email	<%= form.text_field :email %><br><br>
Mobile	<%= form.text_field :mobile %><br><br>
Address	<%= form.text_field :address %><br><br>
Date of Birth	<%= form.date_field  :dob %><br><br>
Date of Joining	<%= form.date_field  :doj %><br><br>
<%= form.submit %>
<% end %>
</div>

<style type="text/css">
	#form{
		align: center;
		color: red;
		border-style: solid;
		padding: 20px 0px;
		width: 250px;
		margin-left: 450px;
		margin-top: 100px;
	}
</style>

app/views/employers/index.html.erb
<h2><%= link_to 'given_access' , new_member_path %></h2>
<h2><%= link_to 'Membership' , members_path ,remote:true %></h2>
<div id="employers">
<h3><%= link_to 'New_Employer' , employers_path %></h3>
<h3><%= link_to 'Employees' , employees_path %></h3>
<h3><%= link_to 'New_Employee' , new_employee_path %></h3>

<h2>Employers</h2>
<table border="1" id="employertable">
	<tr align="center">
		<th>Id</th>
		<th>Name</th>
		<th>email</th>
		<th>Mobile</th>
		<th>Date_of_birth</th>
		<th>Date_of_joining</th>
		<th>Permission As</th>
	</tr>
<% @employers.each do |employer| %>
	<% z = Membership.where(employer_id: employer.id  ,user_role: current_user.id ) %>
	<% rol = Role.find(z.pluck(:role_id)) %>
	<% rr = rol.pluck(:role_name) %>  
  <tr align="center">
	<td align="center"><%= employer.id %> </td>
	<td><%= employer.name %> 		</td>
	<td><%= employer.email%> 		</td>
	<td><%= employer.mobile %>	</td>
	<td><%= employer.dob %>  		</td>
	<td><%= employer.doj %>  		</td>
	<td><%= rol.pluck(:role_name) %>         </td>
	<td><%#= rol.role_name %>         </td>
	<td><%= link_to 'given_access' ,new_member_path(:employer_id => employer.id ,
	:employer_email => employer.email) %></td>
	
	  <td> <%#= link_to 'Detail' ,employer_path(employer.id) %> </td>
 </tr>
<% end %>
</table>
</div>

<style type="text/css">
	#employertable{
		font-size: 20px;
		margin: 0px 80px;
	}
	table{
		width: 1000px;
	}
	tr:nth-child(even){
		background-color: #32a8a2;
	}
	td{
		align: center;
	}
</style>

app/views/employers/new.html.erb
<div id="form" align="center">
<%= form_with model: @employer do |form| %>
Name 	<%= form.text_field :name %><br><br>
Email	<%= form.text_field :email %><br><br>
Mobile	<%= form.text_field :mobile %><br><br>
Address	<%= form.text_field :address %><br><br>
Date of Birth	<%= form.date_field  :dob %><br><br>
Date of Joining	<%= form.date_field  :doj %><br><br>
<%= form.submit %>
<% end %>
</div>

<style type="text/css">
	#form{
		align: center;
		color: red;
		border-style: solid;
		padding: 20px 0px;
		width: 250px;
		margin-left: 450px;
		margin-top: 100px;
	}
</style>

app/views/employers/show.html.erb
<h2>
Id  : <%= @employer.id %><br>
Name : <%= @employer.name %><br> 		
Email :<%= @employer.email%><br> 		
Mobile <%= @employer.mobile %>	<br>
Date of Birth : <%= @employer.dob %> <br>
Date of Joining <%= @employer.doj %> <br>

	<% current_employers(current_user.id , @employer.id) %>
	<% if can? :read ,Membership %>
	<div class="inline">
	<%= button_to 'edit' ,edit_employer_path ,method: :get%> 
	<%= button_to 'destroy' ,employer_path(@employer.id) ,method: :delete %>
	<% end %>
</div>
<br><br>
<td><%= link_to 'given_access' ,new_member_path(:employer_id => @employer.id ,
	:employer_email => @employer.email) %></td> 
<br><br>
<table border="2">
		<tr>
		
			<th>User</th>
			<th>Role</th>
		
		</tr>

<% @members.each do |member| %>
	<% role_name = Role.find(member.role_id) %>
	<% user = User.find(member.user_role) %>
	<tr>
	
		<td><%= user.email %> </td>
		<td><%= role_name.role_name %> </td>
		<td><%= button_to 'edit' ,edit_member_path(member.id) ,method: :get %></td>
		<td><%= button_to 'destroy',member_path(member.id) ,method: :delete  %></td>

	</tr>
	<% end %>
</table>
</h2>

<style type="text/css">
	#employertable{
		font-size: 20px;
		margin: 0px 80px;
	}
	table{
		width: 1000px;
	}
	tr:nth-child(even){
		background-color: #32a8a2;
	}
	td{
		align: center;
	}
</style>