config/routes.rb
Rails.application.routes.draw do
  root to: 'employers#index'
  devise_for :users
  #devise_for :employers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root to: "employees#index"
  resources :employers ,only: [] do
    collection do
      get :acco
      get :get_acco
      get :new
      post :create
    end
  end


  resources :employees ,except: [:show] do
    collection do    
      get "employees_destroy"
    end
  end
  resources :members
  resources :roles 
  resources :designations
  resources :addresses ,except: [:show]
  get "search" ,to: "employees#search"
  
  get "employees/address(/:id)" ,to: "employees#adda" ,as: 'adres'

  get "employees/grouping" ,to: "employees#grouping" 
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # @user = Membership.where(user_role: user.id , user_id: user.id)
    
    
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    # debugger
    # can :read , Employer do |e|
    #   debugger
    # end

  end

  def self.member(user_id , employer_id)
    $user = Membership.where(user_role: user_id , employer_id: employer_id).first
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :employee
  acts_as_paranoid
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/designation.rb
class Designation < ApplicationRecord
	has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
	paginates_per 4
	belongs_to :employer
	has_many :addresses ,dependent: :delete_all #,inverse_of: :address 
	accepts_nested_attributes_for :addresses , allow_destroy: true  ,reject_if: :checking?

	acts_as_paranoid

	has_one_attached :image

	belongs_to :designation


	#validates :first_name , :last_name ,presence: true ,format: { with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/,
   # message: "only allows letters" }
  after_create  :registration_email
	
	validates :doj , :dob  ,presence: true
	validates :email , presence: true ,uniqueness: true
	

	def self.search_employee(search , designate)	
		if designate.nil? or designate == '0'	
      where("name LIKE :q OR email LIKE :q " ,q: "%#{search}%")
    else
    	design = where("designation_id IS :d" ,d: "#{designate}")
    	design.where("first_name LIKE :q OR last_name LIKE :q OR email LIKE :q " ,q: "%#{search}%")
    end
  end

	private
	def checking?(attr)
		attr['country'].blank? and attr['state'].blank?  and attr['city'].blank? and attr['street_address'].blank?
	end
	def registration_email
		
		#EmployeeMailer.new_employee(self.employee).deliver
	end
end

app/models/employer.rb
class Employer < ApplicationRecord
  has_many :employees ,dependent: :destroy
  belongs_to :user
  has_many :memberships ,dependent: :destroy
  after_create :create_admin
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  private
  def create_admin
    employerin = Employer.last
    employersid= employerin.id
    userin = employerin.user_id
    Membership.create(user_id: userin,role_id: 4 ,user_role: userin ,employer_id: employersid)
  end
end

app/models/member.rb
class Member < ApplicationRecord
	belongs_to :role
	belongs_to :user
	belongs_to :employer
	validate :member_validation


	private
	def member_validation
		puts 'start_checking'
		allcheck = Member.where('user_id IS ? AND role_id IS ? AND user_role IS ?AND employer_id IS ?',user_id,role_id,user_role,employer_id)
		repeatrole = Member.where('role_id IS ? AND employer_id IS ? ',role_id,employer_id)
		repeatuser = Member.where('employer_id IS ? AND user_role IS ? ',employer_id,user_role)
	
		if !allcheck.blank?
			errors.add(:user_role , 'this role has already accessed') 
			return false
		elsif !repeatrole.blank?
			errors.add(:role_id , 'role will not repeat')
		elsif !repeatuser.blank?
			errors.add(:user_role,'user will not repeat in same employer')
		else 
			return true 
		end
	end
end

app/models/membership.rb
class Membership < ApplicationRecord
	belongs_to :role
	belongs_to :user
	belongs_to :employer
	validate :member_validation


	private
	def member_validation
		allcheck = Membership.where('user_id IS ? AND role_id IS ? AND user_role IS ?AND employer_id IS ?',user_id,role_id,user_role,employer_id)
		repeatrole = Membership.where('role_id IS ? AND employer_id IS ? ',role_id,employer_id)
		repeatuser = Membership.where('employer_id IS ? AND user_role IS ? ',employer_id,user_role)
	
		if !allcheck.blank?
			errors.add(:user_role , 'this role has already accessed') 
			return false
		elsif !repeatrole.blank?
			errors.add(:role_id , 'role will not repeat')
		elsif !repeatuser.blank?
			errors.add(:user_role,'user will not repeat in same employer')
		else 
			return true 
		end
	end
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :memberships
	has_many :users ,through: :memberships
end

app/models/user.rb
class User < ApplicationRecord
  has_many :memberships
  has_many :employers
  has_many :roles  , through: :memberships
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_role ,only: [:edit , :destroy]
  
  def index
    @roles = Role.all
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_param)
    if @role.save
      redirect_to root_path
    else
      flash[:notice] = "Your details has not submited"
      render 'new'
    end
  end

  def edit
  end

  def update
    @role = Role.update(require_role)
    if @role.save
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @role.destroy
    redirect_to root_path
  end

  
  private

  def role_param
    params.require(:role).permit(:role_name)
  end

  def require_role
    @role = Role.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
	print "dsferwfherui"
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_employers(user_id , employer_id)
		Ability.member(user_id , employer_id)
	end
end

app/helpers/designations_helper.rb
module DesignationsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EMS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%#= javascript_pack_tag 'employees', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
     <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!-- <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" data-mutate-approach="sync"></script> -->
<%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 <%= stylesheet_pack_tag 'application' , 'data-turbolinks-track': 'reload'%>
  </head><div class = "container" align="center">
         <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p></div>
  <body>
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="# " style="color:blueviolet;" ><h3><%= link_to "Employee Management System" ,root_path %></h3></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
     <% if user_signed_in? %>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#"><%= link_to 'Edit profile', edit_user_registration_path    %></a>
      </li>
      <li class="nav-item">
        <%#= link_to 'Add New Employee?', new_employee_path ,:class => "nav-item" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Designations',designations_path %>
      </li>
      <li class="nav-item">
        <%= link_to "designation_group" , employees_grouping_path %>
      </li>
    </ul>
     <%= button_to "Logout", destroy_user_session_path, method: :delete ,:class => "nav-item nav-inline"  %>
     <h4 style="color:red">  <%= current_user.name %>
    <% else %>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#"><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>

      </li>
    </ul>
    <%end %>
  </div>
</nav>
    <%= yield %>
  </body>
</html>